apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-svc-9968
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/gateway-svc-9968
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
